Description:  This template deploys an S3 bucket for storage of recipes.

Resources:
  S3BucketRecipesFree:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-free-recipes-solution", !Ref 'AWS::AccountId' ] ]
  S3BucketRecipesSecret:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ "cand-c3-secret-recipes-solution", !Ref 'AWS::AccountId' ] ]
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
                
  S3BucketVPCFlowLogs:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join [ "-", [ "cand-c3-vpc-flow-logs-solution", !Ref 'AWS::AccountId' ] ]

Outputs:
  BucketNameRecipesFree:
    Value: !Ref 'S3BucketRecipesFree'
    Description: Name of the Amazon S3 bucket that you will upload free recipes to.
    Export:
      Name: BucketNameRecipesFree-Solution
  BucketNameRecipesFreeARN:
    Value: !GetAtt S3BucketRecipesFree.Arn
    Description: Name of the Amazon S3 bucket that you will upload free recipes to.
    Export:
      Name: BucketNameRecipesFree-SolutionARN
  BucketNameRecipesSecret:
    Value: !Ref 'S3BucketRecipesSecret'
    Description: Name of the Amazon S3 bucket that you will upload secret recipes to.
    Export:
      Name: BucketNameRecipesSecret-Solution
  BucketArnVPCFlowLogs:
    Value: !GetAtt S3BucketVPCFlowLogs.Arn
    Description: Arn of the Amazon S3 bucket that have vpc flow logs for this project
    Export:
      Name: BucketArnVPCFlowLogs-Solution
